Tzeng/130 inventory alphabetical sorting
digitalaidseattle/plymouth-housing pull request #33
Opened 2024-10-31 17:29 UTC by aitzeng

## Description

_Give a brief context and description of the code change. Highlight anything you want reviewers to pay attention to._

_The PR should have enough information so someone coming in fresh gets a sense of what's going on, but the details of the overall project can be documented on project.digitalaidseattle.org_

## What type of PR is this? (check all applicable)

- [] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Related Tickets & Documents

https://das-ph-inventory-tracker.atlassian.net/browse/PIT-130

- Related Issue #
- Closes #130

## QA Instructions, Screenshots, Recordings

N/A

2024-11-04 18:49 UTC, bospoort requested changes
Looks good. A few remnants.

2024-11-04 18:49 UTC, bospoort commented on src/pages/inventory/index.tsx
> +      console.log(data.value)
Nit: can we remove the console.logs?

2024-11-04 18:49 UTC, bospoort commented on src/pages/inventory/index.tsx
>        const handler = setTimeout(() => {
remove commented out console log

2024-11-04 18:49 UTC, bospoort commented on src/pages/inventory/index.tsx
>        fetchData();
Another

2024-11-04 22:21 UTC, aitzeng commented on src/pages/inventory/index.tsx
> +      console.log(data.value)
Removed

2024-11-04 22:21 UTC, aitzeng commented on src/pages/inventory/index.tsx
>        const handler = setTimeout(() => {
Removed

2024-11-04 22:21 UTC, aitzeng commented on src/pages/inventory/index.tsx
>        fetchData();
Removed

2024-11-04 22:30 UTC, pingchenchan approved these changes

2024-11-06 19:26 UTC, bospoort approved these changes

2024-11-06 19:29 UTC, merged