#169 Hide dashboard on admin
digitalaidseattle/plymouth-housing pull request #43
Opened 2024-11-15 03:52 UTC by jingtechy

## Description

The PR hides dashboard page for admin 

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Related Tickets & Documents

[PIT-169](https://das-ph-inventory-tracker.atlassian.net/browse/PIT-169)

## QA Instructions, Screenshots, Recordings

It has been tested locally, and the screenshot has been attached to the user story.

2024-11-15 22:17 UTC, bospoort requested changes
I still don't like commenting out code :-) but since this is temporary, we can add a TODO?

2024-11-15 22:17 UTC, bospoort commented on src/menu-items/index.tsx
> +//   DashboardOutlined,
```suggestion
// TODO Commenting out for now until PIT-52 (Admin dashboard) 
//   DashboardOutlined,
```

2024-11-17 22:09 UTC, jingtechy commented
> I still don't like commenting out code :-) but since this is temporary, we can add a TODO?

Yes I've added a TODO comment.

2024-11-23 23:21 UTC, pingchenchan approved these changes

2024-11-26 01:00 UTC, bospoort approved these changes

2024-11-26 01:16 UTC, merged