#176 Hide profile and setting tab
digitalaidseattle/plymouth-housing pull request #45
Opened 2024-11-17 22:21 UTC by jingtechy

## Description

The PR hides the Profile and Settings tabs and only displays the Logout icon.

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Related Tickets & Documents

[PIT-176](https://das-ph-inventory-tracker.atlassian.net/browse/PIT-176)

## QA Instructions, Screenshots, Recordings

It has been tested locally, and the screenshot has been attached to the user story.

2024-11-23 23:23 UTC, pingchenchan approved these changes

2024-11-26 00:47 UTC, aitzeng approved these changes

2024-11-26 00:51 UTC, bospoort requested changes
Can we remove the commented out code? We can always get it back from github if needed.

2024-11-26 00:51 UTC, bospoort commented on src/layout/MainLayout/Header/HeaderContent/Profile/index.tsx
> +//     ReactNode,
Can we remove the commented out line?

2024-11-26 00:51 UTC, bospoort commented on src/layout/MainLayout/Header/HeaderContent/Profile/index.tsx
> +//   Tab,
remove?

2024-11-26 00:51 UTC, bospoort commented on src/layout/MainLayout/Header/HeaderContent/Profile/index.tsx
> +//     Direction,
remove?

2024-12-06 01:10 UTC, bospoort approved these changes

2024-12-06 01:41 UTC, merged