#168 Clean up the header
digitalaidseattle/plymouth-housing pull request #46
Opened 2024-11-21 04:47 UTC by jingtechy

## Description

1. Hide Notification bell for now
2. Remove search box
3. Replace logo with PH’s log
4. Increase margin around PH logo

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Related Tickets & Documents

[PIT-168](https://das-ph-inventory-tracker.atlassian.net/browse/PIT-168)

## QA Instructions, Screenshots, Recordings

It has been tested locally, and the screenshot has been attached to the user story.

2024-11-23 23:26 UTC, pingchenchan approved these changes

2024-11-26 00:45 UTC, bospoort requested changes
Can you leave a comment in the code, why it is commented out? Thanks! Otherwise, looks good. Like the new icon!

2024-11-26 00:45 UTC, bospoort commented on src/layout/MainLayout/Header/HeaderContent/index.tsx
> +// import toolbarItems from '../../../../toolbar-items';
Is this coming back at some point? If not, please remove. Otherwise, can we add //TODO or comment why it is commented out?

2024-11-26 00:45 UTC, bospoort commented on src/layout/MainLayout/Header/HeaderContent/index.tsx
> +      {/* {toolbarItems.items} */}
Can we add the same comment as above?

2024-11-26 06:49 UTC, jingtechy commented on src/layout/MainLayout/Header/HeaderContent/index.tsx
> +      {/* {toolbarItems.items} */}
Yes, I added a comment.

2024-12-03 20:06 UTC, bospoort approved these changes

2024-12-03 21:14 UTC, merged