#163 Architecture design for transaction history
digitalaidseattle/plymouth-housing pull request #63
Opened 2024-12-12 23:39 UTC by jingtechy

## Description

The PR designs the architecture for the backend of the transaction history feature.

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [x] Documentation Update

## Related Tickets & Documents

[PIT-163](https://das-ph-inventory-tracker.atlassian.net/browse/PIT-163)

2024-12-13 21:48 UTC, bospoort requested changes
Looks really good. I made some minor suggestions for parameter name changes and SQL parameters for consistency throughout the system.

2024-12-13 21:48 UTC, bospoort commented on docs/designs/transaction-design.md
> +  - `UserID` (Foreign Key) - References the `Users` table to identify the admin user associated with the transaction.
```suggestion
  - `UserID` (Foreign Key) - References the `Users` table to identify the user (admin or volunteer) associated with the transaction.
```

2024-12-13 21:48 UTC, bospoort commented on docs/designs/transaction-design.md
> +  - `UserID` (Foreign Key) - References the `Users` table to identify the admin user associated with the transaction.
This leads to a good observation. We don't have the capability to track the admin email for transactions. We should. [#196](https://das-ph-inventory-tracker.atlassian.net/browse/PIT-196)

2024-12-13 21:48 UTC, bospoort commented on docs/designs/transaction-design.md
> +  - `TransactionGUID`- Unique identifier for each transaction session (UUID or GUID). Used to correlate multiple entries for the same transaction (e.g., for the same user interacting multiple times w
```suggestion
  - `TransactionGUID`- Unique identifier for each transaction session (UUID or GUID). Used to correlate multiple entries for the same transaction (e.g., for the same user checking out several items within one transaction, or tracking all the items in a welcome basket).
```

2024-12-13 21:48 UTC, bospoort commented on docs/designs/transaction-design.md
> +  - `TotalAmount`: DECIMAL(10, 2), Total amount of the transaction.
```suggestion
  - `Quantity`: DECIMAL(10, 2), Total number of items with *ItemId* in this transaction.
```

2024-12-13 21:48 UTC, bospoort commented on docs/designs/transaction-design.md
> +    TransactionID UNIQUEIDENTIFIER PRIMARY KEY,
```suggestion
        id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,,       
```
This is what we use in the other tables. So for consistency...

2024-12-13 21:48 UTC, bospoort commented on docs/designs/transaction-design.md
> +    UserID INT,
```suggestion
    UserID INT NOT NULL,                                        
```

2024-12-13 21:48 UTC, bospoort commented on docs/designs/transaction-design.md
> +    TransactionGUID UNIQUEIDENTIFIER,
```suggestion
    TransactionID UNIQUEIDENTIFIER  NOT NULL,                  
```

2024-12-13 21:48 UTC, bospoort commented on docs/designs/transaction-design.md
> +    ItemID INT,
```suggestion
    ItemID INT  NOT NULL,                                         
```

2024-12-13 21:48 UTC, bospoort commented on docs/designs/transaction-design.md
> +    TransactionType VARCHAR(50),
```suggestion
    TransactionType VARCHAR(50)  NOT NULL,                          
```

2024-12-13 21:48 UTC, bospoort commented on docs/designs/transaction-design.md
> +    TotalAmount DECIMAL(10, 2),
```suggestion
    Quantity INT  NOT NULL,                         
```
I think this will always be an integer. We could verify though

2024-12-13 21:48 UTC, bospoort commented on docs/designs/transaction-design.md
> +    TransactionDate DATETIME DEFAULT GETDATE(),
```suggestion
    TransactionDate DATETIME DEFAULT GETDATE()  NOT NULL,         
```

2024-12-13 21:48 UTC, bospoort commented on docs/designs/transaction-design.md
> +    FOREIGN KEY (ItemID) REFERENCES Items(ItemID)
Excellent. We should do this in other tables too!

2024-12-13 21:48 UTC, bospoort commented on docs/designs/transaction-design.md
> +CREATE INDEX IX_TransactionHistory_TransactionDate ON TransactionHistory(TransactionDate);
Great idea. Let's wait till we hit performance issues though. But this is the one table that will get very long quickly.

2024-12-13 21:48 UTC, bospoort commented on docs/designs/transaction-design.md
> +  - Parameters: `UserID`, `TransactionGUID`, `ItemID`, `TransactionType`, `TotalAmount`.
Can you match the parameter names with my suggestions throughout the document (if you agree with the names)

2024-12-13 21:48 UTC, bospoort commented on docs/designs/transaction-design.md
> +- **GetTransactionHistory**:
This is a great suggestion. I would like to hold off on implementing these until we have the user stories and the figma designs for the transaction history
- do we want them by user, building, date, category, etc.
- are we going to do client side filtering or server side.

2024-12-13 21:48 UTC, bospoort commented on docs/designs/transaction-design.md
> +    @AdminUserID INT                 -- The ID of the admin requesting transaction history
```suggestion
    @UserID INT                 -- The ID of the admin requesting transaction history
```
I think we want them for volunteers as well

2024-12-13 21:48 UTC, bospoort commented on docs/designs/transaction-design.md
> +### API Endpoints
These are easily exposed through the json file with the other REST API endpoints.

2024-12-16 20:54 UTC, bospoort approved these changes
Great!

2024-12-19 22:06 UTC, bospoort approved these changes
Looks good!!

2024-12-20 01:27 UTC, aitzeng approved these changes

2024-12-20 01:27 UTC, aitzeng commented on docs/designs/transaction-design.md
> +- Front-end sends a POST request to the `/api/transactions` endpoint with transaction details and generates a TransactionGUID for the transaction.
Suggestion to change this to a stored procedure so that only one api call is required to change the inventory and log a transaction at the same time.

2024-12-20 02:43 UTC, merged